[workspace]
members = [
    "apps/server",
    "apps/client",
    "crates/xeonvpn-core",
    "crates/xeonvpn-net",
    "crates/xeonvpn-quic",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["XeonVPN Devs"]
