[package]
name = "xeonvpn-net"
version = "0.1.0"
edition = "2021"

[dependencies]
xeonvpn-core = { path = "../xeonvpn-core" }
 
 [target.'cfg(target_os = "linux")'.dependencies]
 tun = { version = "0.6", features = ["async"] }
 tokio = { version = "1", features = ["full"] }
 tracing = "0.1"
